import assert from 'node:assert/strict';
import fs from 'node:fs';

const root = new URL('../', import.meta.url);
const read = file => fs.readFileSync(new URL(file, root), 'utf8');
const project = read('project.godot');
const scene = read('main.tscn');
const game = read('main.gd');
const data = read('level_data.gd');
const shell = read('web_shell.html');

assert.match(project, /config\/name="Neon Twice"/);
assert.match(project, /run\/main_scene="res:\/\/main\.tscn"/);
assert.match(scene, /script = ExtResource/);
assert.match(game, /MUSIC_BPM|\["music"\]\["bpm"\]/);
assert.match(game, /func _start_quiz/);
assert.match(game, /func _answer_quiz/);
assert.match(game, /quiz_choices/);
assert.match(game, /quiz_time = 10\.0/);
assert.match(game, /%d" % quiz_choices\[i\]/);
assert.match(game, /InputEventScreenTouch/);
assert.match(game, /circuit-punk-game-menu\.mp3/);
assert.match(game, /func _toggle_builder/);
assert.match(game, /func _export_level/);
assert.match(game, /func _import_level/);
assert.match(game, /catapult/);
assert.match(game, /gravity_portal/);
assert.match(game, /func _draw_builder/);
assert.match(game, /func _draw_tiny_skeleton/);
assert.doesNotMatch(game, /laser_gate|LASER TIMING MISS/);
assert.match(game, /RESPAWN CHECKPOINT/);
assert.match(game, /get_viewport_rect\(\)\.size/);
assert.match(data, /static func validate/);
assert.match(data, /moving_platform/);
assert.match(data, /quiz/);
assert.match(shell, /width: 100vw/);
assert.match(shell, /height: 100dvh/);
assert.match(shell, /position: fixed/);
assert.match(shell, /orientationchange/);
assert.match(shell, /window\.location\.reload/);
assert.match(read('export_presets.cfg'), /html\/custom_html_shell="res:\/\/web_shell\.html"/);
assert.doesNotMatch(game, /Puff Quest|Puffo|Meadow/);

console.log('Neon Twice static checks passed.');
