import assert from 'node:assert/strict';
import fs from 'node:fs';

const root = new URL('../', import.meta.url);
const read = file => fs.readFileSync(new URL(file, root), 'utf8');
const project = read('project.godot');
const scene = read('main.tscn');
const game = read('main.gd');
const data = read('level_data.gd');
const shell = read('web_shell.html');

assert.match(project, /config\/name="Neon Twice"/);
assert.match(project, /run\/main_scene="res:\/\/main\.tscn"/);
assert.match(scene, /script = ExtResource/);
assert.match(game, /MUSIC_BPM|\["music"\]\["bpm"\]/);
assert.match(game, /func _start_quiz/);
assert.match(game, /func _answer_quiz/);
assert.match(game, /quiz_choices/);
assert.match(game, /quiz_time = 10\.0/);
assert.match(game, /%d" % quiz_choices\[i\]/);
assert.match(game, /InputEventScreenTouch/);
assert.match(data, /cyberpunk-menu-music\.mp3/);
assert.match(data, /murder-on-the-metrorail\.ogg/);
assert.match(data, /boss-fight\.ogg/);
assert.match(data, /Ghost train pursuit/);
assert.match(data, /"chase_beat": 72\.0/);
assert.match(game, /campaign_catalog/);
assert.match(game, /localStorage/);
assert.match(game, /_level_choice_rect/);
assert.doesNotMatch(game, /MUSIC_OPTIONS|_cycle_music|_music_button_rect\(\)\.has_point/);
assert.match(game, /quiz_streak/);
assert.match(game, /_undo_edit/);
assert.match(game, /_redo_edit/);
assert.match(game, /_paste_selected/);
assert.match(game, /_builder_drag/);
assert.match(game, /_builder_pan/);
assert.match(game, /drag empty space to pan/);
assert.match(game, /_draw_beat_layers/);
assert.match(game, /shield_hits/);
assert.match(game, /invulnerability = max\(invulnerability, 2\.0\)/);
assert.match(game, /catapult_boost_left/);
assert.match(game, /_draw_background_details/);
assert.match(game, /func _toggle_builder/);
assert.match(game, /func _export_level/);
assert.match(game, /func _import_level/);
assert.match(game, /catapult/);
assert.match(game, /gravity_portal/);
assert.match(game, /func _draw_builder/);
assert.match(game, /func _draw_marching_skeleton/);
assert.match(game, /ghost-float-spritesheet\.png/);
assert.match(game, /ghost-attack-spritesheet\.png/);
assert.match(game, /ghost-idle3-spritesheet\.png/);
assert.match(game, /ghost-death-spritesheet\.png/);
assert.match(game, /func _start_ghost_chase/);
assert.match(game, /func _begin_ghost_attack/);
assert.match(game, /func _ghost_try_dodge/);
assert.match(game, /DASH THE GHOST!/);
assert.doesNotMatch(game, /laser_gate|LASER TIMING MISS/);
assert.match(game, /CHECKPOINT %02d/);
assert.match(game, /_draw_landing_trace/);
assert.match(game, /TAP \/ SPACE TO RETRY NOW/);
assert.match(game, /crash_timer/);
assert.match(game, /_jump_beat_event/);
assert.match(game, /PERFECT JUMP/);
assert.match(game, /_draw_metro_background/);
assert.match(game, /_draw_boss_background/);
assert.match(game, /skeleton-run-spritesheet\.png/);
assert.match(game, /draw_texture_rect_region/);
assert.match(game, /Vector2\(450\.0, 594\.0\)/);
assert.ok(fs.existsSync(new URL('../assets/skeleton-run-spritesheet.png', import.meta.url)));
assert.ok(fs.existsSync(new URL('../assets/ghost-float-spritesheet.png', import.meta.url)));
assert.ok(fs.existsSync(new URL('../assets/ghost-attack-spritesheet.png', import.meta.url)));
assert.ok(fs.existsSync(new URL('../assets/ghost-idle3-spritesheet.png', import.meta.url)));
assert.ok(fs.existsSync(new URL('../assets/ghost-death-spritesheet.png', import.meta.url)));
assert.match(game, /_start_chase/);
assert.match(game, /runtime_objects/);
assert.match(game, /quiz_snapshot/);
assert.match(game, /ANSWER REVIEW/);
assert.match(game, /music_last_position/);
assert.match(game, /func _maintain_music/);
assert.match(game, /AUDIO_RESYNC_SECONDS := 0\.28/);
assert.match(game, /func _finish_audio_resync/);
assert.match(game, /RESYNCING BEAT/);
assert.match(game, /INTRO_CLEAR_SECONDS := 6\.0/);
assert.match(game, /func _draw_touch_guide/);
assert.match(game, /func _trigger_ground_slam/);
assert.match(game, /SLAM_INTERVAL_BEATS := 8\.0/);
assert.match(game, /func _draw_slam_effect/);
assert.doesNotMatch(game, /runtime_objects\.append/);
assert.match(game, /var diamonds := 0/);
assert.match(game, /owned_skins/);
assert.match(game, /func _shop_button_rect/);
assert.match(game, /func _shop_button_hit/);
assert.match(game, /func _touch_jump_rect/);
assert.match(game, /func _touch_dash_rect/);
assert.match(game, /var in_intro: bool/);
assert.match(game, /_resume_music\(0\.0\)/);
assert.match(game, /PRISM PULSE/);
assert.match(game, /diamonds \+= 10/);
assert.match(game, /trail_particles/);
assert.match(game, /func _spawn_skin_burst/);
assert.match(game, /func _draw_effect_particle/);
assert.match(game, /run_perfect_jumps/);
assert.match(game, /func _draw_finish_stat/);
assert.match(game, /func _finish_menu_hit/);
assert.match(game, /TOUCH: BACK TO LEVELS/);
assert.match(game, /DIAMONDS EARNED/);
assert.match(game, /ON-BEAT ACCURACY/);
assert.match(game, /MISSED OPPORTUNITIES/);
assert.match(game, /get_viewport_rect\(\)\.size/);
assert.match(data, /static func validate/);
assert.match(data, /moving_platform/);
assert.match(data, /quiz/);
assert.match(shell, /width: 100vw/);
assert.match(shell, /height: 100dvh/);
assert.match(shell, /position: fixed/);
assert.match(shell, /orientationchange/);
assert.match(shell, /window\.location\.reload/);
assert.match(read('export_presets.cfg'), /html\/custom_html_shell="res:\/\/web_shell\.html"/);
assert.doesNotMatch(game, /Puff Quest|Puffo|Meadow/);

console.log('Neon Twice static checks passed.');
